version: 2
updates:
  # Go modules (root module)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "diogoribeiro7"
    labels:
      - "dependencies"
      - "go"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "diogoribeiro7"
    labels:
      - "dependencies"
      - "github-actions"
